ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-robot-localization \
    i2c-tools \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install --no-cache-dir smbus2
